#+TITLE: Tracker
#+DESCRIPTION: file related to the torrent tracker
#+PROPERTY: :tangle "./tracker.js"

* Explanation
There is no explanation so far, this is just a placeholder
* Code
** Imports
#+BEGIN_SRC js :tangle yes
import dgram from 'dgram';
import { Buffer } from 'buffer';
import { urlParse } from 'url';
import crypto from 'crypto';
import { genInfoHash, getTorrentSize } from './torrent-handler.js';
import { genPeerId, getPeerGroup } from './generic-utils.js';
#+END_SRC

** Methods
*** udpSend
Sends a message through the udp socket
#+BEGIN_SRC js :tangle yes
const udpSend = (torrent, message, rawUrl, callback) => {
    const url = urlParse(rawUrl);
    socket.send(message, 0, message.length, url.port, url.host, callback);
};
#+END_SRC
*** responseType
Interprets the response type
More info: #[[responseType]]
#+BEGIN_SRC js :tangle yes
const responseType = response => {
    const action = response.readUInt32BE(0);
    if(action === 0) return 'connect';
    if(action === 1) return 'announce';
    else return 'failure';
};
#+END_SRC

*** buildConnectionRequest
Builds the connection request
More info: [[#connectReq]]
#+BEGIN_SRC js :tangle yes
const buildConnectionRequest = () => {
    //1. buffer allocation
    const buf = Buffer.alloc(16);

    //2. connection_id
    buf.writeUInt32BE(0x417, 0);
    buf.writeUInt32BE(0x27101980, 4);

    //3. action type
    buf.writeUInt32BE(0, 8);

    //4. transaction_id
    crypto.randomBytes(4).copy(buf, 12);

    return buf;
};
#+END_SRC

*** parseConnectionResponse
Parses the response to the connectionRequest
More info: [[#connectRes]]
#+BEGIN_SRC js :tangle yes
const parseConnectionResponse = response => {
    return {
        action: response.readUInt32BE(0),
        transactionId: response.readUInt32BE(4),
        connectionId: response.slice(8)
    };
};
#+END_SRC

*** buildAnnounceRequest
Builds the announce request
More info: [[#announceReq]]
#+BEGIN_SRC js :tangle yes
const buildAnnounceRequest = (connectionId, torrent, port = 6881) => {
    //1. allocate buffer
    const buf = Buffer.allocateUnsafe(98);

    //2. connection_id
    connectionId.copy(buf, 0);

    //3. action
    buf.writeUInt32BE(1, 8);

    //4. transaction_id
    crypto.randomBytes(4).copy(buf, 12);

    //5. info hash
    genInfoHash(torrent).copy(buf, 16);

    //6. peer_id
    genPeerId().copy(buf, 36);

    //7. downloaded
    Buffer.alloc(8).copy(buf, 56);

    //8. left
    getTorrentSize(torrent).copy(buf, 64);

    //9. uploaded
    Buffer.alloc(8).copy(buf, 72);

    //10. event
    buf.writeUInt32BE(0, 80);

    //11. ip address
    buf.writeUInt32BE(0, 80);

    //12. key
    crypto.randomBytes(4).copy(buf, 88);

    //13. num_want
    buf.writeInt32BE(-1, 92);

    //14. port
    buf.writeUInt32BE(port, 96);

    return buf;
};
#+END_SRC

*** parseAnnounceResponse
Parses the response to the announce request
More info: [[#announceRes]]
#+BEGIN_SRC js :tangle yes
const parseAnnounceResponse = response => {
    return {
        action: response.readUInt32BE(0),
        transaction_id: response.readUInt32BE(4),
        leechers: response.readUInt32BE(8),
        seeders: readUInt32BE(12),
        peers: getPeerGroup(response.slice(20), 6).map(address => {
            return {
                ip: address.slice(0, 4).join('.'),
                port: address.readUInt16BE(4)
            };
        })
    };
};
#+END_SRC

*** getPeers
Get a list of the torrent peers
More info: [[#getPeers]]
#+BEGIN_SRC js :tangle yes
const getPeers = (torrent, callback) => {
    const url = urlParse(torrent.announce.toString("utf8"));
    const socket = dgram.createSocket('udp4');

    udpSend(socket, buildConnectionRequest(), url);

    socket.on('message', response => {
        if(responseType(response) === 'connect'){
            const connectionResponse = parseConnectionResponse(response);
            const announceRequest = buildAnnounceRequest(connectionResponse.connectionId);
            udpSend(socket, announceRequest, url);
        }
        else if(responseType(response) === 'announce'){
            const announceResponse = parseAnnounceResponse(response);
            callback(announceResponse.peers);
        }
    });
};
#+END_SRC

** Exports
#+BEGIN_SRC js :tangle yes
export {
    getPeers
};
#+END_SRC

* Reference
** Torrent Requests
The requests need to be buffers with specific values in certain positions (for more info, see http://www.bittorrent.org/beps/bep_0015.html).

** getPeers
:PROPERTIES:
:CUSTOM_ID: getPeers
:END:
Get url and create udp socket; send connection request with udpSend();
On receiving message, check the type with responseType() and handle it accordingly;
If the message type is connect, then the connection response is parsed with parseConnectionResponse(), the request is built with buildAnnounceRequest(), and the message request is sent with udpSend();
If the message type is announce, then the response is parsed with parseAnnounceResponse(), and the callback function is called.

** responseType
:PROPERTIES:
:CUSTOM_ID: responseType
:END:
Gets the response and reads the type.
** buildConnectionRequest
:PROPERTIES:
:CUSTOM_ID: connectReq
:END:
This is the connect request
The buffer's first 8 bytes (from position 0 to position 7) are a 64-bit integer with the value of 0x41727101980;
the next 4 bytes (from position 8 to 11) must be an 32-bit integer describing the action (in this case, connect, the value is 0);
then, the final 4 bytes (from position 12 to 16) form the transaction id, a 32-bit integer with whatever random value the id will be.
#+BEGIN_SRC dot
Offset  Size            Name            Value
0       64-bit integer  protocol_id     0x41727101980
8       32-bit integer  action          0
12      32-bit integer  transaction_id
16
#+END_SRC
*** 1. buffer allocation
Allocating the 16-bit buffer, the size of the message.
*** 2. connection_id
Creating the connection_id with the value stated by the documentation (0x41727101980). It must be created as two separate 32-bit integers because node doesn't support 64-bit integers.
*** 3. action type
Passing the action type to the buffer (0 in this case, for connect)
*** 4. transaction_id
Since this needs to be a random value, the crypto module can be used. After importing it, and after passing all the other values to the buffer, the random value can be generated with the randomBytes method, specifyng the number of bytes it should return; And then, with the copy method, it is copied to the message buffer, with the offset of 12, setting the starting position

** parseConnectionResponse
:PROPERTIES:
:CUSTOM_ID: connectRes
:END:
Parsing the response to the connect request
Much simpler than creating the request itself, the response is received, and then every part is separated into a property of an object, which is returned.
The response structure is similar to the request (see below), but the action is the first value, then the transaction_id, and then the connection_id.
To separate them easily, the first 4 bytes are read as the action (starting at 0), the following four are read as the transaction_id, and for last, since the connection_id is a 64-bit integer, it's easier to just splice the buffer instead of reading it as two halves and trying to join them afterwards.
#+BEGIN_SRC dot
Offset  Size            Name            Value
0       32-bit integer  action          0 // connect
4       32-bit integer  transaction_id
8       64-bit integer  connection_id
16
#+END_SRC

** buildAnnounceRequest
:PROPERTIES:
:CUSTOM_ID: announceReq
:END:
This is the announce request
It follows the same idea of the connection request, but it has several more values. It is 98 bytes long. It would be too long to explain every part individually, so just check the graph below.

Note: this is the announce request for ipv4 addresses. For ipv6, check the documentation linked in the Torrent Requests section.
#+BEGIN_SRC dot
Offset  Size    Name    Value
0       64-bit integer  connection_id
8       32-bit integer  action          1 // announce
12      32-bit integer  transaction_id
16      20-byte string  info_hash
36      20-byte string  peer_id
56      64-bit integer  downloaded
64      64-bit integer  left
72      64-bit integer  uploaded
80      32-bit integer  event           0 // 0: none; 1: completed; 2: started; 3: stopped
84      32-bit integer  IP address      0 // default
88      32-bit integer  key
92      32-bit integer  num_want        -1 // default
96      16-bit integer  port
98
#+END_SRC

*** 1. allocate the buffer
Simple, like in the connect request. Just allocating the buffer, but instead of the 16 bytes the connectRequest used, this one uses 98 bytes.
Also, this one is being allocated with Buffer.allocUnsafe, which uses an pre-allocated internal node buffer pool, making it faster, but not guaranteeing zeroes in all values.
Being honest, I'm not sure why I'm using it here, just saw a guy using it online and decided to give it a try. Really don't know if using the regullar Buffer.alloc will be too much of a hit in performance for such a large(r) buffer, or if it's size makes it inefficient, but hey, if it works, it works.

*** 2. connection_id
The connection id received from parsing the connect request response.

*** 3. action
Again, just like in the connection request, this value indicates what type of request this is, or what action is to be executed. Here, the value should be 1, which is announce

*** 4. transaction_id
The transaction id works the same as the connection id: a randomly generated id that identifies that transaction.

*** 5. info_hash
The info hash is a hashed version of all the info on the torrent. Looks very complicated, ends up being very simple (to understand, of course. I just know I'm in for a ride when I get to the implementation of handling this part).
*Not implemented yet, will update this when it is.*

*** 6. peer_id
The peer id is an id you assign to the peer, so, like the other ids in this request, self-explanatory.

*** 7. downloaded
As far as I understand, it's the amount already downloaded.

*** 8. left
Reflecting downloaded, this one is about how much is left to download (this one seems like it is also going to be a pain to implement, but who knows?).

*** 9. uploaded
Just wingin' it here, but my guess would be how much has been uploaded, just like downloaded. But not sure, it's kinda hard to search info about these individual properties (even the official docs I've linked before don't seem to individually explain these).

*** 10. event
Warns about an event. The types of events are listed in the announce request graph above this section.

*** 11. ip address
It's becoming an common theme with these last ones that I just guess what they are (Still writing everything, haven't had a chance to actually see and use some of these methods yet), but it looks like this one is just the IP of (probably) the receiver.

*** 12. key
A key, not sure exactly what for, but a key nonetheless. It seems like it can just be a random 4-byte value.

*** 13. num_want
The number of peers the client wants to receive. Assuming here that -1 is something akin to unlimited.

*** 14. port
The port the client is listening. Apparently, BitTorrent standardized using ports between 6881-6889, so I've got 6881 as the default for the method arg, but it can be overloaded.

** parseAnnounceReponse
:PROPERTIES:
:CUSTOM_ID: announceRes
:END:
Parsing the response to the announce request
More complicated than it looked for me. The layout is in the graph below, but up until the seeders, it was easy: just like the connect response, just get the value at the exact position. But the peers, that's harder. The number of peers is not fixed, so it needs to be dynamic. In the generic utils file, there's the getPeerGroup method, the explanation will be there, and after, they're mapped to a callback, and returned as (I hope) a nice array of peers.
*slice: interprets it as an array, starts at byte 20, gets the next 6 bytes as the specification says.
Note: Just as it was it building the announce, this format of parsing it is for ipv4 requests. ipv6 are a little different.

#+BEGIN_SRC dot
Offset      Size            Name            Value
0           32-bit integer  action          1 // announce
4           32-bit integer  transaction_id
8           32-bit integer  interval
12          32-bit integer  leechers
16          32-bit integer  seeders
20 + 6 * n  32-bit integer  IP address
24 + 6 * n  16-bit integer  TCP port
20 + 6 * N

#+END_SRC
